# Generated by Django 6.0.1 on 2026-03-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountcredential',
            name='code',
        ),
        migrations.AddField(
            model_name='accountcredential',
            name='generated_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Сгенерированный код'),
        ),
        migrations.AddField(
            model_name='accountcredential',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Верифицировано'),
        ),
        migrations.AddField(
            model_name='accountcredential',
            name='user_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Введенный код'),
        ),
    ]
