# Generated by Django 6.0.1 on 2026-03-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceoffer',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на товар'),
        ),
    ]
