# Generated by Django 6.0.1 on 2026-03-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_marketplaceoffer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceoffer',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Последнее обновление цены'),
        ),
    ]
