# Generated by Django 6.0.1 on 2026-03-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_marketplaceoffer_last_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceoffer',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
